"""
Bank configuration — top 30 Indian banks
Sender emails, keywords, and parsing hints
"""

# ── Top 30 Indian banks with their alert sender addresses ─────
BANK_SENDERS = {
    # Private Banks
    "alerts@hdfcbank.net":              "HDFC",
    "hdfcbank@hdfcbank.net":            "HDFC",
    "nachautoemailer@hdfcbank.net":     "HDFC",
    "alerts@icicibank.com":             "ICICI",
    "icicibank@icicibank.com":          "ICICI",
    "axisindiaalerts@axisbank.com":     "Axis",
    "alerts@axisbank.com":              "Axis",
    "alerts@kotak.com":                 "Kotak",
    "kotak@kotak.com":                  "Kotak",
    "alerts@indusind.com":              "IndusInd",
    "alerts@yesbank.in":                "Yes Bank",
    "alerts@idfcfirstbank.com":         "IDFC First",
    "alerts@federalbank.co.in":         "Federal Bank",
    "alerts@rblbank.com":               "RBL",
    "alerts@bandhanbank.com":           "Bandhan",
    "alerts@southindianbank.com":       "South Indian Bank",
    "alerts@kvb.co.in":                 "Karur Vysya",
    "alerts@cityunionbank.com":         "City Union Bank",
    # Public Banks
    "sbialerts@sbi.co.in":              "SBI",
    "alerts@sbi.co.in":                 "SBI",
    "alerts@sbicard.com":               "SBI",
    "alerts@bankofbaroda.com":          "Bank of Baroda",
    "alerts@pnb.co.in":                 "PNB",
    "alerts@canarabank.in":             "Canara Bank",
    "alerts@unionbankofindia.com":      "Union Bank",
    "alerts@idbi.co.in":                "IDBI",
    "alerts@bankofindia.co.in":         "Bank of India",
    "alerts@centralbankofindia.co.in":  "Central Bank",
    "alerts@indianbank.in":             "Indian Bank",
    "alerts@ucobank.com":               "UCO Bank",
    "alerts@psbindia.com":              "Punjab & Sind Bank",
    # Foreign Banks
    "hsbc@hsbc.co.in":                  "HSBC",
    "hsbc@mail.hsbc.co.in":             "HSBC",
    "hsbc@mandatehq.com":               "HSBC",
    "alerts@sc.com":                    "Standard Chartered",
    "scalerts@sc.com":                  "Standard Chartered",
    "citibank@citi.com":                "Citibank",
    "alerts@dbs.com":                   "DBS",
    "alerts@db.com":                    "Deutsche Bank",
}

# ── Bank name keywords for subject/body detection ─────────────
BANK_KEYWORDS = {
    "HDFC":               ["hdfc", "hdfcbank"],
    "ICICI":              ["icici", "icicidirect"],
    "Axis":               ["axis bank", "axisbank"],
    "Kotak":              ["kotak mahindra", "kotak bank"],
    "IndusInd":           ["indusind"],
    "Yes Bank":           ["yes bank", "yesbank"],
    "IDFC First":         ["idfc first", "idfcfirst"],
    "Federal Bank":       ["federal bank", "federalbank"],
    "RBL":                ["rbl bank", "rblbank"],
    "SBI":                ["state bank", "sbi"],
    "Bank of Baroda":     ["bank of baroda", "bob"],
    "PNB":                ["punjab national", "pnb"],
    "Canara Bank":        ["canara bank"],
    "Union Bank":         ["union bank of india"],
    "IDBI":               ["idbi bank"],
    "HSBC":               ["hsbc"],
    "Standard Chartered": ["standard chartered", "stanchart"],
    "Citibank":           ["citibank", "citi bank"],
    "DBS":                ["dbs bank"],
    "Deutsche Bank":      ["deutsche bank"],
}

# ── Transaction mode keywords ─────────────────────────────────
MODE_KEYWORDS = {
    "UPI":          ["upi", "vpa", "bhim", "gpay", "phonepe", "paytm upi"],
    "Credit Card":  ["credit card", "cc", "visa", "mastercard", "rupay", "amex"],
    "Debit Card":   ["debit card", "atm", "pos", "swipe"],
    "NACH":         ["nach", "ach", "mandate", "ecs", "auto debit"],
    "Net Banking":  ["net banking", "neft", "rtgs", "imps", "internet banking"],
    "Wallet":       ["wallet", "paytm wallet", "mobikwik"],
}

# ── VPA business keyword mapping ──────────────────────────────
VPA_MERCHANT_MAP = {
    # Food & Dining
    "zomato":           ("Zomato",          "Food & Dining",        "spend"),
    "swiggy":           ("Swiggy",          "Food & Dining",        "spend"),
    "dominos":          ("Dominos",         "Food & Dining",        "spend"),
    "dominopizza":      ("Dominos",         "Food & Dining",        "spend"),
    "mcdonalds":        ("McDonald's",      "Food & Dining",        "spend"),
    "kfc":              ("KFC",             "Food & Dining",        "spend"),
    "pizzahut":         ("Pizza Hut",       "Food & Dining",        "spend"),
    "starbucks":        ("Starbucks",       "Food & Dining",        "spend"),
    "burgerking":       ("Burger King",     "Food & Dining",        "spend"),
    "subway":           ("Subway",          "Food & Dining",        "spend"),
    "foodsquare":       ("Food Square",     "Food & Dining",        "spend"),
    "eatsure":          ("EatSure",         "Food & Dining",        "spend"),
    "dunzo":            ("Dunzo",           "Groceries",            "spend"),
    # Groceries
    "blinkit":          ("Blinkit",         "Groceries",            "spend"),
    "bigbasket":        ("BigBasket",       "Groceries",            "spend"),
    "zepto":            ("Zepto",           "Groceries",            "spend"),
    "jiomart":          ("JioMart",         "Groceries",            "spend"),
    "dmart":            ("DMart",           "Groceries",            "spend"),
    "grofers":          ("Blinkit",         "Groceries",            "spend"),
    # Shopping
    "amazon":           ("Amazon",          "Shopping",             "spend"),
    "flipkart":         ("Flipkart",        "Shopping",             "spend"),
    "myntra":           ("Myntra",          "Shopping",             "spend"),
    "ajio":             ("Ajio",            "Shopping",             "spend"),
    "meesho":           ("Meesho",          "Shopping",             "spend"),
    "nykaa":            ("Nykaa",           "Shopping",             "spend"),
    "snapdeal":         ("Snapdeal",        "Shopping",             "spend"),
    "tatacliq":         ("Tata CLiQ",       "Shopping",             "spend"),
    # Travel & Transport
    "uber":             ("Uber",            "Travel & Transport",   "spend"),
    "olacabs":          ("Ola",             "Travel & Transport",   "spend"),
    "rapido":           ("Rapido",          "Travel & Transport",   "spend"),
    "irctc":            ("IRCTC",           "Travel & Transport",   "spend"),
    "makemytrip":       ("MakeMyTrip",      "Travel & Transport",   "spend"),
    "goibibo":          ("Goibibo",         "Travel & Transport",   "spend"),
    "indigo":           ("IndiGo",          "Travel & Transport",   "spend"),
    "airindia":         ("Air India",       "Travel & Transport",   "spend"),
    "ixigo":            ("Ixigo",           "Travel & Transport",   "spend"),
    "pranaam":          ("Pranaam",         "Travel & Transport",   "spend"),
    "yatri":            ("Yatri",           "Travel & Transport",   "spend"),
    # Fuel
    "indianoil":        ("Indian Oil",      "Fuel",                 "spend"),
    "hpcl":             ("HPCL",            "Fuel",                 "spend"),
    "bpcl":             ("BPCL",            "Fuel",                 "spend"),
    "reliance.bp":      ("Reliance BP",     "Fuel",                 "spend"),
    # Entertainment & OTT
    "netflix":          ("Netflix",         "Entertainment & OTT",  "spend"),
    "hotstar":          ("Hotstar",         "Entertainment & OTT",  "spend"),
    "spotify":          ("Spotify",         "Entertainment & OTT",  "spend"),
    "primevideo":       ("Amazon Prime",    "Entertainment & OTT",  "spend"),
    "sonyliv":          ("Sony LIV",        "Entertainment & OTT",  "spend"),
    "zee5":             ("Zee5",            "Entertainment & OTT",  "spend"),
    "jiocinema":        ("JioCinema",       "Entertainment & OTT",  "spend"),
    "bookmyshow":       ("BookMyShow",      "Entertainment & OTT",  "spend"),
    # Health & Medical
    "apollopharmacy":   ("Apollo Pharmacy", "Health & Medical",     "spend"),
    "apollo":           ("Apollo",          "Health & Medical",     "spend"),
    "pharmeasy":        ("PharmEasy",       "Health & Medical",     "spend"),
    "1mg":              ("1mg",             "Health & Medical",     "spend"),
    "practo":           ("Practo",          "Health & Medical",     "spend"),
    "medplus":          ("MedPlus",         "Health & Medical",     "spend"),
    # Utilities & Bills
    "airtel":           ("Airtel",          "Utilities & Bills",    "spend"),
    "jio":              ("Jio",             "Utilities & Bills",    "spend"),
    "bsnl":             ("BSNL",            "Utilities & Bills",    "spend"),
    "vodafone":         ("Vi",              "Utilities & Bills",    "spend"),
    "idea":             ("Vi",              "Utilities & Bills",    "spend"),
    "tatapower":        ("Tata Power",      "Utilities & Bills",    "spend"),
    "bses":             ("BSES",            "Utilities & Bills",    "spend"),
    "bescom":           ("BESCOM",          "Utilities & Bills",    "spend"),
    "adanielectricity": ("Adani Electricity","Utilities & Bills",   "spend"),
    # Investments & Finance
    "zerodha":          ("Zerodha",         "Investments & Finance","investment"),
    "groww":            ("Groww",           "Investments & Finance","investment"),
    "upstox":           ("Upstox",          "Investments & Finance","investment"),
    "kuvera":           ("Kuvera",          "Investments & Finance","investment"),
    "etmoney":          ("ETMoney",         "Investments & Finance","investment"),
    "bse":              ("BSE/MF SIP",      "Investments & Finance","investment"),
    "nse":              ("NSE/MF SIP",      "Investments & Finance","investment"),
    "bseltd":           ("BSE/MF SIP",      "Investments & Finance","investment"),
    "mfcentral":        ("Mutual Fund",     "Investments & Finance","investment"),
    "camsonline":       ("CAMS/MF",         "Investments & Finance","investment"),
    "kfintech":         ("KFintech/MF",     "Investments & Finance","investment"),
    # Insurance
    "lic":              ("LIC",             "Insurance",            "spend"),
    "hdfclife":         ("HDFC Life",       "Insurance",            "spend"),
    "sbilife":          ("SBI Life",        "Insurance",            "spend"),
    "icicipruli":       ("ICICI Pru Life",  "Insurance",            "spend"),
    "starhealth":       ("Star Health",     "Insurance",            "spend"),
    "niacl":            ("New India Assurance","Insurance",         "spend"),
    # Education
    "byjus":            ("BYJU'S",          "Education",            "spend"),
    "unacademy":        ("Unacademy",       "Education",            "spend"),
    "vedantu":          ("Vedantu",         "Education",            "spend"),
    "coursera":         ("Coursera",        "Education",            "spend"),
    "udemy":            ("Udemy",           "Education",            "spend"),
    # Subscriptions
    "google":           ("Google",          "Subscriptions",        "spend"),
    "apple":            ("Apple",           "Subscriptions",        "spend"),
    "linkedin":         ("LinkedIn",        "Subscriptions",        "spend"),
    "microsoft":        ("Microsoft",       "Subscriptions",        "spend"),
    # Credit Card Payments (settlement)
    "hdfccc":           ("HDFC Credit Card","Credit Card Payment",  "settlement"),
    "icicipay":         ("ICICI Credit Card","Credit Card Payment", "settlement"),
    "sbicard":          ("SBI Card",        "Credit Card Payment",  "settlement"),
    "axiscard":         ("Axis Credit Card","Credit Card Payment",  "settlement"),
    "hsbccc":           ("HSBC Credit Card","Credit Card Payment",  "settlement"),
    # P2P payment apps (resolve merchant from VPA further)
    "paytm":            None,  # Need further resolution
    "phonepe":          None,
    "gpay":             None,
    "bhim":             None,
}

# ── NACH/ECS merchant patterns ────────────────────────────────
NACH_MERCHANT_MAP = {
    "bse":              ("BSE/MF SIP",          "Investments & Finance","investment"),
    "nse":              ("NSE/MF SIP",           "Investments & Finance","investment"),
    "bse limited":      ("BSE/MF SIP",           "Investments & Finance","investment"),
    "cams":             ("CAMS/MF SIP",          "Investments & Finance","investment"),
    "kfintech":         ("KFintech/MF SIP",      "Investments & Finance","investment"),
    "zerodha":          ("Zerodha SIP",          "Investments & Finance","investment"),
    "groww":            ("Groww SIP",            "Investments & Finance","investment"),
    "lic":              ("LIC Premium",          "Insurance",            "spend"),
    "hdfc life":        ("HDFC Life",            "Insurance",            "spend"),
    "sbi life":         ("SBI Life",             "Insurance",            "spend"),
    "loan":             ("Loan EMI",             "EMI & Loans",          "settlement"),
    "emi":              ("EMI",                  "EMI & Loans",          "settlement"),
    "home loan":        ("Home Loan EMI",        "EMI & Loans",          "settlement"),
    "car loan":         ("Car Loan EMI",         "EMI & Loans",          "settlement"),
}
